export const mockDispatcherStats = {
    totalDeliveries: 156,
    activeDeliveries: 12,
    completedDeliveries: 144,
    totalEarnings: 23450.75,
};

export const mockDispatcherOrders = [
    {
        _id: 'order_dispatch_001',
        products: [
            { name: 'Fresh Tomatoes', quantity: 5, price: 45.00 },
            { name: 'Carrots', quantity: 3, price: 28.00 },
        ],
        totalCost: 309.00,
        orderStatus: 'in_transit',
        paymentStatus: 'paid',
        createdAt: '2024-01-15T08:30:00Z',
        deliveryAddress: '123 Main Street, Sandton, Johannesburg',
        estimatedDeliveryTime: '2024-01-16T14:00:00Z',
        riderName: 'Thabo Mokoena',
        farmName: 'Green Valley Farm',
        customerName: 'Sarah Johnson',
        customerPhone: '+27 82 123 4567',
    },
    {
        _id: 'order_dispatch_002',
        products: [
            { name: 'Sweet Corn', quantity: 10, price: 35.00 },
            { name: 'Spinach', quantity: 2, price: 32.00 },
        ],
        totalCost: 414.00,
        orderStatus: 'ready',
        paymentStatus: 'paid',
        createdAt: '2024-01-14T10:15:00Z',
        deliveryAddress: '456 Oak Avenue, Pretoria',
        estimatedDeliveryTime: '2024-01-15T16:00:00Z',
        riderName: 'Sipho Ndlovu',
        farmName: 'Sunset Ridge Farm',
        customerName: 'Michael Brown',
        customerPhone: '+27 83 234 5678',
    },
    {
        _id: 'order_dispatch_003',
        products: [
            { name: 'Strawberries', quantity: 2, price: 85.00 },
            { name: 'Fresh Tomatoes', quantity: 3, price: 45.00 },
        ],
        totalCost: 285.00,
        orderStatus: 'delivered',
        paymentStatus: 'paid',
        createdAt: '2024-01-13T09:45:00Z',
        deliveryAddress: '789 Pine Road, Rosebank, Johannesburg',
        estimatedDeliveryTime: '2024-01-14T12:00:00Z',
        riderName: 'Lerato Molefe',
        farmName: 'Golden Harvest Farm',
        customerName: 'David van der Merwe',
        customerPhone: '+27 84 345 6789',
    },
    {
        _id: 'order_dispatch_004',
        products: [
            { name: 'Carrots', quantity: 4, price: 28.00 },
            { name: 'Spinach', quantity: 1, price: 32.00 },
        ],
        totalCost: 144.00,
        orderStatus: 'in_transit',
        paymentStatus: 'paid',
        createdAt: '2024-01-12T14:20:00Z',
        deliveryAddress: '321 Elm Street, Bryanston, Johannesburg',
        estimatedDeliveryTime: '2024-01-13T15:00:00Z',
        riderName: 'David van der Merwe',
        farmName: 'Fresh Fields Farm',
        customerName: 'Nomsa Dlamini',
        customerPhone: '+27 85 456 7890',
    },
    {
        _id: 'order_dispatch_005',
        products: [
            { name: 'Sweet Corn', quantity: 8, price: 35.00 },
            { name: 'Fresh Tomatoes', quantity: 2, price: 45.00 },
        ],
        totalCost: 370.00,
        orderStatus: 'ready',
        paymentStatus: 'pending',
        createdAt: '2024-01-11T11:30:00Z',
        deliveryAddress: '654 Maple Drive, Centurion',
        estimatedDeliveryTime: '2024-01-12T13:00:00Z',
        riderName: 'Nomsa Dlamini',
        farmName: 'Organic Valley Farm',
        customerName: 'John Smith',
        customerPhone: '+27 86 567 8901',
    },
    {
        _id: 'order_dispatch_006',
        products: [
            { name: 'Fresh Tomatoes', quantity: 6, price: 45.00 },
            { name: 'Carrots', quantity: 2, price: 28.00 },
        ],
        totalCost: 326.00,
        orderStatus: 'delivered',
        paymentStatus: 'paid',
        createdAt: '2024-01-10T13:45:00Z',
        deliveryAddress: '987 Cedar Lane, Midrand',
        estimatedDeliveryTime: '2024-01-11T14:00:00Z',
        riderName: 'Thabo Mokoena',
        farmName: 'Green Valley Farm',
        customerName: 'Lisa Thompson',
        customerPhone: '+27 87 678 9012',
    },
];

export const deliveryAddresses = [
    '123 Main Street, Sandton, Johannesburg',
    '456 Oak Avenue, Pretoria',
    '789 Pine Road, Rosebank, Johannesburg',
    '321 Elm Street, Bryanston, Johannesburg',
    '654 Maple Drive, Centurion',
    '987 Cedar Lane, Midrand',
    '147 Birch Boulevard, Fourways',
    '258 Willow Way, Randburg',
];

export const riderNames = [
    'Thabo Mokoena',
    'Sipho Ndlovu',
    'Lerato Molefe',
    'David van der Merwe',
    'Nomsa Dlamini',
    'John Smith',
    'Sarah Johnson',
    'Michael Brown',
];

export const customerNames = [
    'Sarah Johnson',
    'Michael Brown',
    'David van der Merwe',
    'Nomsa Dlamini',
    'John Smith',
    'Lisa Thompson',
    'Emma Wilson',
    'James Davis',
]; 