export const mockFarmerStats = {
    totalProducts: 24,
    activeOrders: 8,
    totalRevenue: 45678.90,
    averageRating: 4.7,
};

export const mockProducts = [
    {
        _id: 'prod_001',
        name: 'Fresh Tomatoes',
        category: 'vegetables',
        price: 45.00,
        unit: 'kg',
        quantity: 150,
        description: 'Organic tomatoes from our greenhouse',
        harvestDate: '2024-01-15',
        location: 'Johannesburg, Gauteng',
        isOrganic: true,
        isFeatured: true,
        status: 'active',
        images: [],
    },
    {
        _id: 'prod_002',
        name: 'Sweet Corn',
        category: 'grains',
        price: 35.00,
        unit: 'kg',
        quantity: 200,
        description: 'Sweet yellow corn, perfect for braai',
        harvestDate: '2024-01-10',
        location: 'Pretoria, Gauteng',
        isOrganic: false,
        isFeatured: true,
        status: 'active',
        images: [],
    },
    {
        _id: 'prod_003',
        name: 'Carrots',
        category: 'vegetables',
        price: 28.00,
        unit: 'kg',
        quantity: 120,
        description: 'Fresh orange carrots, great for cooking',
        harvestDate: '2024-01-12',
        location: 'Johannesburg, Gauteng',
        isOrganic: true,
        isFeatured: false,
        status: 'active',
        images: [],
    },
    {
        _id: 'prod_004',
        name: 'Spinach',
        category: 'vegetables',
        price: 32.00,
        unit: 'kg',
        quantity: 80,
        description: 'Fresh spinach leaves, perfect for salads',
        harvestDate: '2024-01-14',
        location: 'Pretoria, Gauteng',
        isOrganic: true,
        isFeatured: false,
        status: 'active',
        images: [],
    },
    {
        _id: 'prod_005',
        name: 'Strawberries',
        category: 'fruits',
        price: 85.00,
        unit: 'kg',
        quantity: 60,
        description: 'Sweet strawberries, perfect for desserts',
        harvestDate: '2024-01-13',
        location: 'Johannesburg, Gauteng',
        isOrganic: true,
        isFeatured: true,
        status: 'active',
        images: [],
    },
];

export const mockFarmerOrders = [
    {
        _id: 'order_farmer_001',
        products: [
            { name: 'Fresh Tomatoes', quantity: 5, price: 45.00 },
            { name: 'Carrots', quantity: 3, price: 28.00 },
        ],
        totalCost: 309.00,
        orderStatus: 'confirmed',
        paymentStatus: 'paid',
        createdAt: '2024-01-15T08:30:00Z',
        deliveryAddress: '123 Main Street, Sandton, Johannesburg',
        estimatedDeliveryTime: '2024-01-16T14:00:00Z',
        riderName: 'Thabo Mokoena',
        farmName: 'Green Valley Farm',
    },
    {
        _id: 'order_farmer_002',
        products: [
            { name: 'Sweet Corn', quantity: 10, price: 35.00 },
            { name: 'Spinach', quantity: 2, price: 32.00 },
        ],
        totalCost: 414.00,
        orderStatus: 'preparing',
        paymentStatus: 'paid',
        createdAt: '2024-01-14T10:15:00Z',
        deliveryAddress: '456 Oak Avenue, Pretoria',
        estimatedDeliveryTime: '2024-01-15T16:00:00Z',
        riderName: 'Sipho Ndlovu',
        farmName: 'Green Valley Farm',
    },
    {
        _id: 'order_farmer_003',
        products: [
            { name: 'Strawberries', quantity: 2, price: 85.00 },
            { name: 'Fresh Tomatoes', quantity: 3, price: 45.00 },
        ],
        totalCost: 285.00,
        orderStatus: 'delivered',
        paymentStatus: 'paid',
        createdAt: '2024-01-13T09:45:00Z',
        deliveryAddress: '789 Pine Road, Rosebank, Johannesburg',
        estimatedDeliveryTime: '2024-01-14T12:00:00Z',
        riderName: 'Lerato Molefe',
        farmName: 'Green Valley Farm',
    },
    {
        _id: 'order_farmer_004',
        products: [
            { name: 'Carrots', quantity: 4, price: 28.00 },
            { name: 'Spinach', quantity: 1, price: 32.00 },
        ],
        totalCost: 144.00,
        orderStatus: 'in_transit',
        paymentStatus: 'paid',
        createdAt: '2024-01-12T14:20:00Z',
        deliveryAddress: '321 Elm Street, Bryanston, Johannesburg',
        estimatedDeliveryTime: '2024-01-13T15:00:00Z',
        riderName: 'David van der Merwe',
        farmName: 'Green Valley Farm',
    },
    {
        _id: 'order_farmer_005',
        products: [
            { name: 'Sweet Corn', quantity: 8, price: 35.00 },
            { name: 'Fresh Tomatoes', quantity: 2, price: 45.00 },
        ],
        totalCost: 370.00,
        orderStatus: 'ready',
        paymentStatus: 'pending',
        createdAt: '2024-01-11T11:30:00Z',
        deliveryAddress: '654 Maple Drive, Centurion',
        estimatedDeliveryTime: '2024-01-12T13:00:00Z',
        riderName: 'Nomsa Dlamini',
        farmName: 'Green Valley Farm',
    },
];

export const farmNames = [
    'Green Valley Farm',
    'Sunset Ridge Farm',
    'Golden Harvest Farm',
    'Fresh Fields Farm',
    'Organic Valley Farm',
];

export const deliveryAddresses = [
    '123 Main Street, Sandton, Johannesburg',
    '456 Oak Avenue, Pretoria',
    '789 Pine Road, Rosebank, Johannesburg',
    '321 Elm Street, Bryanston, Johannesburg',
    '654 Maple Drive, Centurion',
    '987 Cedar Lane, Midrand',
    '147 Birch Boulevard, Fourways',
    '258 Willow Way, Randburg',
];

export const riderNames = [
    'Thabo Mokoena',
    'Sipho Ndlovu',
    'Lerato Molefe',
    'David van der Merwe',
    'Nomsa Dlamini',
    'John Smith',
    'Sarah Johnson',
    'Michael Brown',
]; 