// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { VunarcPayments$Type } from "./VunarcPayments";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["VunarcPayments"]: VunarcPayments$Type;
    ["contracts/VunarcPayments.sol:VunarcPayments"]: VunarcPayments$Type;
  }

  interface ContractTypesMap {
    ["VunarcPayments"]: GetContractReturnType<VunarcPayments$Type["abi"]>;
    ["contracts/VunarcPayments.sol:VunarcPayments"]: GetContractReturnType<VunarcPayments$Type["abi"]>;
  }
}
