// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { VunaletPayments$Type } from "./VunaletPayments";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["VunaletPayments"]: VunaletPayments$Type;
    ["contracts/VunaletPayments.sol:VunaletPayments"]: VunaletPayments$Type;
  }

  interface ContractTypesMap {
    ["VunaletPayments"]: GetContractReturnType<VunaletPayments$Type["abi"]>;
    ["contracts/VunaletPayments.sol:VunaletPayments"]: GetContractReturnType<VunaletPayments$Type["abi"]>;
  }
}
